---
# maintains versions and can overwrite all.yml
pharos:
  validator:
    version: v0.12.2
    commit: f301031a
    genesis_url: https://raw.githubusercontent.com/PharosNetwork/resources/refs/heads/main/mainnet.genesis
    version_url: https://raw.githubusercontent.com/PharosNetwork/resources/refs/heads/main/mainnet.version
    snapshot_url:
