---
# maintains versions and can overwrite all.yml
pharos:
  validator:
    version: v0.1.3
    node_ip: "95.217.4.193"
    node_id: 3fb06aa005dedb4b4014be2fd1c046e9e968b73d1bfaa15b02796b36295808a8
    snapshot_url: https://snapshot.dplabs-internal.com/testnet/snapshot-2025-08-29-15-44.tar.gz
  prune:
    version: v0.1.3
