---
- name: Install Pushgateway
  hosts: all
  become: true
  gather_facts: true
  vars:
    project: "{{ group_names[0] }}"
    system_architecture: "{{ architecture_map[ansible_architecture] | default(ansible_architecture) }}"
  vars_files:
    - group_vars/all.yml
    - group_vars/default.yml
    - group_vars/vault.yml
  tasks:
    - name: Set service_identifier
      ansible.builtin.set_fact:
        service_identifier: "{{ project }}-{{ pushgateway.service_identifier }}"

    - name: Include common handlers
      ansible.builtin.include_role:
        name: common
    - name: Include pushgateway role
      ansible.builtin.include_role:
        name: pushgateway
