---
# maintains mainnet inventory grouped by project names
all:
  vars:
    env: mainnet
  children:
    pharos:
      hosts:
        validator.pharos.mainnet.encapsulate.xyz:
          type: validator
