---
# maintains testnet inventory grouped by project names
all:
  vars:
    env: testnet
  children:
    pharos:
      hosts:
        validator.pharos.testnet.encapsulate.xyz:
          type: validator
