---
# maintains testnet inventory grouped by project names
all:
  vars:
    env: testnet
  children:
    pharos:
      hosts:
        validator.pharos.testnet.encapsulate.xyz:
          type: validator
        pharos_prune_host:
          ansible_host: validator.pharos.testnet.encapsulate.xyz
          type: prune
