---
- name: Include user creation task
  ansible.builtin.include_tasks: tasks/create_user_and_directories.yml
  vars:
    home: "{{ pushgateway_home_dir }}"
    directories: "{{ pushgateway_directories }}"
    log_file_path: "{{ pushgateway_log_file_path }}"

- name: Include Download, Unarchive and Copy Binary task
  ansible.builtin.include_tasks: tasks/extract_binary.yml
  vars:
    extracted_binary_dir: "pushgateway-{{ pushgateway.version }}.{{ system_arch }}"
    source_url: "{{ pushgateway.source_url }}"
    suffix_url: "v{{ pushgateway.version }}/pushgateway-{{ pushgateway.version }}.{{ system_arch }}.{{ pushgateway.file_extension }}"
    binary_dest_path: "{{ pushgateway_bin_dir }}/{{ service_identifier }}"
    extracted_binary_path: "{{ extracted_binary_dir }}/{{ pushgateway_default_binary_name }}"

- name: Copy pushgateway systemd file
  ansible.builtin.template:
    src: systemd.service.j2
    dest: /etc/systemd/system/{{ service_identifier }}.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload service
    - Restart service
