---
- name: Include node vars files
  ansible.builtin.include_vars: "{{ item }}"
  loop:
    - roles/node/defaults/main.yml
    - roles/node/vars/main.yml

- name: Prune the database
  ansible.builtin.shell: >
    ./{{ node_binaries.pharos_cli.dest_binary_name }} prune --c {{ node_config_file_path }} --enable_auto_prune
  args:
    chdir: "{{ node_bin_dir }}"
    executable: /bin/bash
  environment:
    LD_PRELOAD: "{{ node_lib_dir }}/{{ node_binaries.pharos_evm_lib.dest_binary_name }}"
