---
- name: Create tmp directory
  ansible.builtin.file:
    path: "{{ tmp_dir }}/{{ service_identifier }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Unarchive the binary
  ansible.builtin.unarchive:
    src: "{{ pharos.validator.source_url }}/pharos-{{ pharos.validator.version }}.tar.gz"
    dest: "{{ tmp_dir }}/{{ service_identifier }}"
    remote_src: true
    owner: root
    group: root
    mode: "0755"

- name: Copy binary file
  ansible.builtin.copy:
    src: "{{ tmp_dir }}/{{ service_identifier }}/bin/{{ node_service_default_binary_name }}"
    dest: "{{ node_bin_dir }}/{{ service_identifier }}"
    remote_src: true
    owner: root
    group: root
    force: true
    mode: "0755"
  notify:
    - Restart service

- name: Copy lib file
  ansible.builtin.copy:
    src: "{{ tmp_dir }}/{{ service_identifier }}/bin/libevmone.so"
    dest: "{{ node_lib_dir }}/libevmone.so.0.15"
    remote_src: true
    owner: root
    group: root
    force: true
    mode: "0755"
  notify:
    - Restart service

- name: Copy Version file
  ansible.builtin.copy:
    src: "{{ tmp_dir }}/{{ service_identifier }}/bin/VERSION"
    dest: "{{ node_bin_dir }}/VERSION"
    remote_src: true
    owner: root
    group: root
    force: true
    mode: "0644"
  notify:
    - Restart service

- name: Clear tmp directory
  ansible.builtin.file:
    path: "{{ tmp_dir }}/{{ service_identifier }}"
    state: absent
