---
- name: Create tmp directory
  ansible.builtin.file:
    path: "{{ tmp_dir }}/{{ service_identifier }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Unarchive the binary
  ansible.builtin.unarchive:
    src: "{{ pharos.validator.source_url }}/{{ pharos.validator.version }}/pharos-{{ pharos.validator.version }}.tar.gz"
    dest: "{{ tmp_dir }}/{{ service_identifier }}"
    remote_src: true
    owner: root
    group: root
    mode: "0755"

- name: Copy binary files
  ansible.builtin.copy:
    src: "{{ item.extracted_path }}"
    dest: "{{ item.dest_path }}"
    remote_src: true
    owner: root
    group: root
    force: true
    mode: "0755"
  with_items: "{{ path_mapping }}"
  notify:
    - Restart service

- name: Clear tmp directory
  ansible.builtin.file:
    path: "{{ tmp_dir }}/{{ service_identifier }}"
    state: absent
