---
- name: Include the specific network's vars file
  ansible.builtin.include_vars:
    file: vars/ufw_rules.yml

- name: Apply UFW rules for each node type
  ansible.builtin.include_tasks: tasks/apply_ufw_rules.yml
  loop: "{{ node_ufw_rules }}"

- name: Include user creation task
  ansible.builtin.include_tasks: tasks/create_user_and_directories.yml
  vars:
    home: "{{ node_home_dir }}"
    directories: "{{ node_directories }}"
    log_file_path: "{{ node_log_file_path }}"

- name: Include initilise database task
  ansible.builtin.include_tasks: initilise_database.yml
  when: init_db | default(false) | bool

- name: Include extract binaries task
  ansible.builtin.include_tasks: extract_binaries.yml
  vars:
    extracted_dir: "{{ tmp_dir }}/{{ service_identifier }}/bin"
    path_mapping:
      - extracted_path: "{{ extracted_dir }}/{{ node_binaries.pharos_default.default_binary_name }}"
        dest_path: "{{ node_bin_dir }}/{{ service_identifier }}"
      - extracted_path: "{{ extracted_dir }}/{{ node_binaries.pharos_evm_lib.default_binary_name }}"
        dest_path: "{{ node_lib_dir }}/{{ node_binaries.pharos_evm_lib.dest_binary_name }}"
      - extracted_path: "{{ extracted_dir }}/{{ node_binaries.pharos_version.default_binary_name }}"
        dest_path: "{{ node_bin_dir }}/{{ node_binaries.pharos_version.dest_binary_name }}"

- name: Copy public cert file
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ service_identifier }}"
    group: "{{ service_identifier }}"
    mode: "0644"
  loop:
    - { src: "{{ env }}/bls.pub", dest: "{{ node_bls_pub_key_file_path }}" }
    - { src: "{{ env }}/prime.pub", dest: "{{ node_prime_pub_key_file_path }}" }
  notify:
    - Restart service

- name: Fetch secrets from HCP Vault and save to files
  when:
    - type == 'validator'
    - fetch_validator_keys | default(false) | bool
  block:
    - name: Fetch bls key and save
      ansible.builtin.include_tasks: tasks/get_and_save_vault_secret.yml
      vars:
        vault_secret_source_path: "{{ project }}/{{ org }}/{{ type }}/{{ node_bls_key_file_name }}"
        secret_destination_path: "{{ node_bls_key_file_path }}"
        secret_type: key

    - name: Fetch prime key and save
      ansible.builtin.include_tasks: tasks/get_and_save_vault_secret.yml
      vars:
        vault_secret_source_path: "{{ project }}/{{ org }}/{{ type }}/{{ node_prime_key_file_name }}"
        secret_destination_path: "{{ node_prime_key_file_path }}"
        secret_type: key

- name: Copy node configuration templates
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ service_identifier }}"
    group: "{{ service_identifier }}"
    mode: "0644"
  loop:
    - { src: "{{ env }}/launch.conf.j2", dest: "{{ node_launch_conf_file_path }}" }
    - { src: "{{ env }}/mygrid.env.json.j2", dest: "{{ node_mygrid_env_file_path }}" }
    - { src: "{{ env }}/mygrid.conf.json.j2", dest: "{{ node_mygrid_conf_file_path }}" }
    - { src: "{{ env }}/general.env.j2", dest: "{{ node_environment_general_file_path }}" }
    - { src: "{{ env }}/monitor.conf.j2", dest: "{{ node_monitor_conf_file_path }}" }
    - { src: "{{ env }}/cubenet.conf.j2", dest: "{{ node_cubenet_conf_file_path }}" }
  notify:
    - Restart service

- name: Copy systemd systemd service file
  ansible.builtin.template:
    src: "{{ env }}/systemd.service.j2"
    dest: /etc/systemd/system/{{ service_identifier }}.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload service
    - Restart service
